"""delete column from office table

Revision ID: 8a8d15886d51
Revises: 901e1ed6507a
Create Date: 2021-07-14 16:26:56.637155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8d15886d51'
down_revision = '901e1ed6507a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Office', 'Department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Office', sa.Column('Department', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
