"""empty message

Revision ID: 901e1ed6507a
Revises: 
Create Date: 2021-07-14 15:41:02.789144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901e1ed6507a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Office_id', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Department_id', sa.Integer(), nullable=True),
    sa.Column('Position_id', sa.Integer(), nullable=True),
    sa.Column('Salary', sa.String(length=50), nullable=True),
    sa.Column('Full_name', sa.String(length=50), nullable=True),
    sa.Column('Login', sa.String(length=50), nullable=True),
    sa.Column('Password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('City', sa.String(length=50), nullable=True),
    sa.Column('Department', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Position')
    op.drop_table('Office')
    op.drop_table('Employee')
    op.drop_table('Department')
    # ### end Alembic commands ###
